config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" #creates about path
  get "carouseltest" => "pages#carouseltest" #creates carouseltest path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "100x100>" }
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def carouseltest
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end 
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class='container'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Bucketlist", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li>
            <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-user"></span> Log In
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span> Home
            <% end %>
          </li>
          <li><%= link_to about_path do %>
            <span class="glyphicon glyphicon-book"></span> About
          <% end %>
          </li>

        <% else %>
          <li>
            <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus"></span> New Pin
           <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span> Home
            <% end %>
          </li>
          <li><%= link_to edit_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span> Profile
              <% end %>
          </li>
          <li><%= link_to carouseltest_path do %>
              <span class="glyphicon glyphicon-picture"></span> Gallery
          <% end %>
          </li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-road"></span> Logout
          <% end %>
          </li>
        <%end%> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |name,msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info")%>
	<%end%>  

		<%= yield %>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
		<h1>Welcome to the future home of <b>Bucket List</b></h1>
		<% if user_signed_in? %>
		Welcome to the Member's Section
		<% else %>
			<p>
			<%= link_to "Sign Up", new_user_registration_path,class: "btn btn-primary btn-md" %>
			</p>
		<%end%>
</div>

app/views/pages/about.html.erb
<div class = "jumbotron" >
<h1>About Bucketlist</h1>
<p>Keep track of things you have dreamed of doing and find people that can help you do it!   <%= link_to "Sign Up",new_user_registration_path,class: "btn btn-primary btn-lg" %></p>
</div>
</div>
<div class = "container">
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Find things you want to do!
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Post and Share it on Bucketlist!
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Find people to help you do it!
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/carouseltest.html.erb
<div id="carousel-example-generic" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

    <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <!-- Slide 1-->
            <div class="item active">
                <img src="https://farm8.staticflickr.com/7203/13159698144_1d44b782dd_o.jpg" width="2470" height="988" alt="9360190815_c7f5843590_o"></a>
                <div class="carousel-caption">
              <h1><b>VIETNAM</b></h1>
              <h2><p>TEXT HOLDER</p></h2>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign Up</a></p>
            </div>
          </div>

            <!-- Slide 2-->
              <div class="item">
                  <img src="https://farm4.staticflickr.com/3800/13159698504_e04dfbb479_o.jpg" width="2470" height="988" alt="4290747095_69fe65e04c_o"></a>
                  <div class="carousel-caption">
                      <h1>CHINA</h1>
                      <p>TEXT HOLDER</p>
                  </div>
              </div>

          <!-- Slide 3-->
            <div class="item">
                <img src="https://farm8.staticflickr.com/7150/13159698514_b7e012c8ea_o.jpg" width="2470" height="988" alt="4290746163_9521d4791e_o"></a>
                <div class="carousel-caption">
                    <h1>SWITZERLAND</h1>
                    <p>TEXT HOLDER</p>
                </div>
            </div>
          </div>



  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
		<h1>Welcome to the future home of Bucketlist</h1>
		<% if user_signed_in? %>
		Welcome to the Member's Section
		<% else %>
			<p>
			<%= link_to "Sign In",new_user_session_path,class: "btn btn-default btn-lg"%>
			<%= link_to "Sign Up", new_user_registration_path,class: "btn btn-primary btn-lg" %>
			</p>
		<%end%>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New pin</h1>
	</div>
		<div class="panel-body">

			<%= render 'form' %>
		</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path%>
	</div>

</div>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.email if @pin.user %></strong></p>
         <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
      <% end %>

      </div>
    </div>
  </div>
</div>